/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElButtonGroup: typeof import('element-plus/es').ElButtonGroup
  const ElCheckboxGroup: typeof import('element-plus/es').ElCheckboxGroup
}
